version: "3.9"
services:
  db:
    image: mysql:8.3.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: book-db
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: "3308"
    ports:
      - "3308:3308"
    expose:
      - "3308"
    networks:
      - xfrontier-network
  xfrontier-book:
    image: cabula/xfrontier-book
    restart: always
    build: ./xfrontier-book
    working_dir: /xfrontier-book
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/book-db?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.DATASOURCE.DRIVER_CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_FLYWAY_ENABLED: true
      SPRING_FLYWAY_LOCATIONS: classpath:db/
      SPRING_FLYWAY_URL: jdbc:mysql://db:3308/book-db?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_FLYWAY_USER: root
      SPRING_FLYWAY_PASSWORD: admin123
    ports:
      - "80:80"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - xfrontier-network
networks:
  xfrontier-network:
    driver: bridge
    
    