CREATE TABLE IF NOT EXISTS `books` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `title` varchar(250) NOT NULL,
  `author` varchar(180) NOT NULL,
  `isbn` varchar(13) NOT NULL,
  `launch_date` date NOT NULL,
  `registration_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_date` datetime,
  `created_by` int NOT NULL,
  `last_modified_by` int,
  `active` tinyint NOT NULL DEFAULT 1,
  `book_status` varchar(20) NOT NULL,
  `shipping_rate` decimal(10,2) NOT NULL, 
  `price` decimal(10,2) NOT NULL,
  `observation` varchar(250) NULL,
  `reason_cancellation` varchar(250) NULL,  
  `category_id` bigint,
  UNIQUE KEY `uk_isbn` (`isbn`),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_book_category` FOREIGN KEY (`category_id`) REFERENCES `category` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;